### ISSUE TITLE
Release dwn-server

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/dwn-server#16]
Dependency: 

* https://github.com/TBD54566975/dwn-server/issues/19

Stretch goals: 

* Add how to sync from your client. 
* Add how to connect to our hosted DWNs. This would be great; it's the part that makes Web5 a remote experience.

Some good docs already started on this [here](https://github.com/TBD54566975/dwn-server#running-the-server). Probably a good starting point to get these going, and before closing this issue will need to point to released versions (GitHub tags or Docker tags) rather than main.

When feature-complete for Phase 4 (BTC Miami), please issue a release of `dwn-server` as a stable basis for docs:

* Git tag
* NPM
* Docker
* ...is that it?

Heard from @csuwildcat today that you may be mostly ready here for BTC Miami, and @chris-tbd is prepping a Tutorial/Guide for running this on the dev site. A released version is the prereq for locking that down. 🤘🏻

**Comment by ALRubinger** [comment]
We're going to simply link to `README` on the repo, using a version by the way of a SHA, per @michaelneale

**Comment by michaelneale** [comment]
I have documented this too on the readme: https://github.com/TBD54566975/dwn-server/blob/main/README.md#running-a-specific-version

**Comment by ALRubinger** [comment]
Yep, closing this per @michaelneale comments on how we refer to this, in README at https://github.com/TBD54566975/dwn-server/blob/173dc1acc910740b3d06b4fe8597dad1069068b3/README.md
