### ISSUE TITLE
Implement cloud native stores

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/dwn-server#23]
related to https://github.com/TBD54566975/dwn-server/issues/10 (and perhaps after it) it may be worth considering implementations of MessageStore and DataStore which are "cloud native" ie blob stores (like s3) as well as key/value stores, allowing DWN to run in a "serverless" type of environment on AWS and GCP. 

Note this is could be a little odd given that the D in DWN is decentralized but for some users, this would be useful.

**Comment by adam4leos** [comment]
closing this as internal collaboration is addressing requested feature atm
