### ISSUE TITLE
Create Contributing.md (BTC-Miami work phase 4)

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/dwn-server#27]
There is a [contributing file in the project template repo](https://github.com/TBD54566975/tbd-project-template/blob/main/CONTRIBUTING.md), copy that file please make sure you update the links and then add the tweaks we discussed below. 

From our call, update your file to resemble [this](https://github.com/TBD54566975/dwn-sdk-js/blob/main/CONTRIBUTING.md) Contributing file in our `dwn-sdk-js` repo. You should be able to primarily copy and paste and add some tweaks to tailor it to your repo.  

Things to include: 
- Highlight labels they should be aware of 'help-wanted', 'good-first-issue', etc
- how to know if it's being worked on `WIP` or not '**assigned to nobody'** filter, navigate them there or add a link like the ex repo
- **Process to follow when working on an issue** 
- Where they should be posting questions, feature request, etc, discord? 

@nitro-neal @mistermoe

**Comment by EbonyLouis** [comment]
Hi @nitro-neal, I know there's a lot of work to be done before BTC Miami. I also really need this done before then as well. How are you guys looking time-wise? Is this something you guys will be able to get done?

**Comment by adam4leos** [comment]
has been addressed in https://github.com/TBD54566975/dwn-server/pull/58 
closing this one
cc @EbonyLouis
