### ISSUE TITLE
Consider replacing some tests with a more robust method of testing, such as writing Playwright tests

### ISSUE THREAD

**Issue by diehuxx** [TBD54566975/dwn-server#50]
### Background:
Consider replacing some tests with a more robust method of testing, such as writing Playwright tests

### Task Details:
- Write test that run in a browser to verify that the `dwn-response` header can be read from the `fetch()` response when CORS mode is enabled.
> Playwright tests

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by adam4leos** [comment]
linking with https://github.com/TBD54566975/dwn-server/issues/18

**Comment by hkwi** [comment]
picking up this

**Comment by EbonyLouis** [comment]
@hkwi Hey, how are things going? would you still like to work on this issue?
