### ISSUE TITLE
Replace eslint `sort-imports` rule with prettier plugin

### ISSUE THREAD

**Issue by adam4leos** [TBD54566975/dwn-server#57]
### Background:
Replace eslint `sort-imports` rule with prettier plugin 

### Task Details:
currently we have an [eslint rule supporting `sort-imports` rule](https://github.com/TBD54566975/dwn-server/blob/main/.eslintrc.cjs#L34C1-L34C1). 

```typescript
'sort-imports': [
      'error',
      {
        ignoreCase: true,
        ignoreDeclarationSort: false,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'single', 'multiple'],
        allowSeparatedGroups: true,
      },
    ],
```

- We'd like to remove this rule from eslint and instead use plugin for prettier, possibly https://github.com/trivago/prettier-plugin-sort-imports, to match the eslint rule as close as possible.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by Opssy** [comment]
@adam4leos  I need more clearification

**Comment by adam4leos** [comment]
@Opssy currently we have an [eslint rule supporting `sort-imports` rule](https://github.com/TBD54566975/dwn-server/blob/main/.eslintrc.cjs#L34C1-L34C1). 

```typescript
'sort-imports': [
      'error',
      {
        ignoreCase: true,
        ignoreDeclarationSort: false,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'single', 'multiple'],
        allowSeparatedGroups: true,
      },
    ],
```

We'd like to remove this rule from eslint and instead use plugin for prettier, possibly https://github.com/trivago/prettier-plugin-sort-imports
to match the eslint rule as close as possible atm

**Comment by Opssy** [comment]
okay

**Comment by EbonyLouis** [comment]
@Opssy Hi, is this an issue you'd like to work on for Hacktoberfest?

**Comment by Opssy** [comment]
@EbonyLouis 
Yes

**Comment by EbonyLouis** [comment]
@Opssy yay! its been assigned to you. 

 I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 
 > to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [is now open!](https://hacktoberfest.com/auth/) Reach out if you need any help 🥳

**Comment by EbonyLouis** [comment]
@jerempy thanks!
