### ISSUE TITLE
Add test coverage for `dwn-server.ts` file

### ISSUE THREAD

**Issue by adam4leos** [TBD54566975/dwn-server#60]
### Background:
Currently we're missing test coverage for `dwn-server.ts` file. 

### Task Details:
- please add some test to cover `dwn-server.ts` file.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by adam4leos** [comment]
Linking related test issues https://github.com/TBD54566975/dwn-server/issues/50 & https://github.com/TBD54566975/dwn-server/issues/49

**Comment by captain-Akshay** [comment]
"picking this up" @adam4leos

**Comment by EbonyLouis** [comment]
@captain-Akshay Hey, how are things going with this issue? Is this something you still want to work on?

**Comment by captain-Akshay** [comment]
@EbonyLouis i was so focused on the developer.tbd.website but i will complete this one !right away
