### ISSUE TITLE
Add tests for `process-handlers.ts` file

### ISSUE THREAD

**Issue by adam4leos** [TBD54566975/dwn-server#61]
### Background:
Currently we're missing tests for `process-handlers.ts` file.

### Task Details:
- please add some to cover `process-handlers.ts` file. 

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by adam4leos** [comment]
Linking related test issues https://github.com/TBD54566975/dwn-server/issues/50 & https://github.com/TBD54566975/dwn-server/issues/49

**Comment by captain-Akshay** [comment]
"picking this up"

**Comment by VarnikaB** [comment]
picking this up

**Comment by EbonyLouis** [comment]
@captain-Akshay Yay another issue 🥳! 

I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 

> to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [is now OPEN.](https://hacktoberfest.com/auth)

**Comment by EbonyLouis** [comment]
@VarnikaB Hey, thanks for your enthusiasm to contribute. 😊 Someone got in just a bit ahead of you on this issue, but don't worry! We have other open `Hacktoberfest` tagged issues that you might find interesting. 

- [developer.tbd.website](https://github.com/TBD54566975/developer.tbd.website/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee)
- [web5-js](https://github.com/TBD54566975/web5-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
- [dwn-server](https://github.com/TBD54566975/dwn-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
- [dwn-sdk-js](https://github.com/TBD54566975/dwn-sdk-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

Also, we'll be adding more issues throughout the month of October, so there will be plenty of opportunities to jump in. If for any reason the current assignee can't proceed with this one, I'll definitely keep you both in mind and reach out. keep an eye on our `events-and-updates` channel in [discord](https://discord.gg/tbd). Thanks for spending Hacktoberfest with us! 🍁

**Comment by EbonyLouis** [comment]
@captain-Akshay Hey, how are things going with this issue? Is this something you still want to work on?
