### ISSUE TITLE
Document methods in the repo

### ISSUE THREAD

**Issue by adam4leos** [TBD54566975/dwn-server#64]
### Background:
We're (unfortunately) lacking method docs, and having some would be amazing.

### Task Details:
Consider covering methods in the repo, especially public and less straightforward, with some jsdocs style comment 

example 
```typescript
/**
   * Handler for opening websocket event - `connection`.
   * Sets listeners for `message`, `pong`, `close`, and `error` events.
   */
#handleConnection(socket: WebSocket, _request: IncomingMessage): void {
  const dwn = this.dwn;
  // ...rest of the code...
``` 

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by MaticSulc** [comment]
Picking this up! :)

**Comment by EbonyLouis** [comment]
@MaticSulc yay! I've assigned it to you! 

I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 

> to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [is now OPEN.](https://hacktoberfest.com/auth)

**Comment by EbonyLouis** [comment]
Hey @MaticSulc would you still like to work on this issue?

**Comment by KhoiUna** [comment]
> Hey @MaticSulc would you still like to work on this issue?

Can I pick this one up if it's not being worked on?

**Comment by EbonyLouis** [comment]
Hey @KhoiUna yes you can work on it, thanks!

**Comment by KhoiUna** [comment]
@EbonyLouis Submitted a [PR](https://github.com/TBD54566975/dwn-server/pull/82)
